name: dockge

services:
  dockge:
    image: docker.io/louislam/dockge:1.5.0
    container_name: dockge
    restart: unless-stopped
    ports:
      - 5001:5001
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - dockge-data:/app/data
      - dockge-stacks:/opt/stacks
    environment:
      - DOCKGE_STACKS_DIR=/opt/stacks
      - DOCKGE_ENABLE_CONSOLE=true

volumes:
  dockge-data:
    name: dockge-data
    driver: local
  dockge-stacks:
    name: dockge-stacks
    driver: local
