services:
  openlist:
    image: docker.io/openlistteam/openlist:v4.1.9
    container_name: openlist
    user: '0:0'
    volumes:
      - openlist-data:/opt/openlist/data
    ports:
      - '5244:5244'
    environment:
      - UMASK=022
    restart: unless-stopped

volumes:
  openlist-data:
    name: openlist-data
    driver: local
